### PR TITLE
Destroy should only return false when removal of session truely fails.

### LINKED ISSUE #36: PHP 7 and redis session caching: Session object destruction failed.
We have been caching sessions with Redis in our Zend Framework 2 project (using zend-session 2.5.2) on PHP 5.6.

After upgrading from PHP 5.6 to PHP 7.0.4, we get PHP warnings like `session_regenerate_id(): Session object destruction failed.  ID: user (path: tcp://host:port?weight=1&amp;timeout=3)` and `session_destroy(): Session object destruction failed` when users are logged out.

When discussing the issue on stackoverflow [here](http://stackoverflow.com/questions/36130603/redis-session-caching-with-php-7-and-zf2-session-object-destruction-failed), it was suggested that this might be a bug in zend-session.

### PR DESCRIPTION
**Pull request by rarog**
Finally fixes #36 

Until this commit, the Cache adapter still fails. This mimics the behaviour of the fix in DbTableGateway.php.

### CODE REVIEW

**Comment by markushausammann** [comment]
Please merge!

**Comment by Ocramius** [comment]
Tests are missing

**Comment by markushausammann** [comment]
@rarog can you provide the tests?

**Comment by rarog** [comment]
Sorry, I had those ready since long time, but never commited them, as I didn't manage to set up a local testing environment.

**Comment by rarog** [comment]
I give up so far, I'm just shooting into the dark, without being sure to hit the target. Can somebody help me resolving the issue with the test? I think I almost got it, but I'm not sure how to work around "expected to be a reference, value given" problem, so the parameter is passed by reference to the mocked function.

**Comment by rarog** [comment]
@Ocramius It seems, I can't mock for the 2nd test properly due to limitations of the framework (https://github.com/phpspec/prophecy/issues/225)

If it is enough, I'd leave the first test in place and remove the 2nd.

**Comment by weierophinney** [comment]
@rarog I've pushed a change (f7eac66) that accomplishes what is needed here. Essentially, the cache `getItem()` method needs the second argument returned by reference. I've done so, and it now passes.

**Comment by weierophinney** [comment]
Thanks, @rarog

**Comment by markushausammann** [comment]
Thanks! Finally we can use redis session caching.

**Pull request merged**
